In [91]:
#import laiberies 
import pandas as pd 
import numpy as np

In [92]:
data = pd.read_excel(r'/Users/sanjaymagar/Desktop/Code IT data analysis project /Ecommerce Sales Analysis.xlsx')

In [93]:
data.head(5)

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,2013,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,2013,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,2013,2013-06-13,2013-06-17,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,2012,2012-10-11,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,2012,2012-10-11,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [94]:
data.columns

Index(['Row ID', 'Order ID', 'Year', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [95]:
data.describe()

,Row ID,Year,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2012.722934,2013-04-30 19:20:02.401441024,2013-05-04 18:20:49.229537792,55190.379428,229.858001,3.789574,0.156203,28.656896
min,1.000000,2011.000000,2011-01-04 00:00:00,2011-01-08 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,2012.000000,2012-05-23 00:00:00,2012-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,2013.000000,2013-06-27 00:00:00,2013-06-30 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,2014.000000,2014-05-15 00:00:00,2014-05-19 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,2014.000000,2014-12-31 00:00:00,2015-01-06 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000
std,2885.163629,1.124039,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108

In [96]:
data.isna().sum()

Row ID           0
Order ID         0
Year             0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [97]:
# Replacing the value
data['Discount'] = data['Discount'].replace(0.00,np.nan)

In [98]:
data['Discount']

0        NaN
1        NaN
2        NaN
3       0.45
4       0.20
        ...
9989    0.20
9990     NaN
9991    0.20
9992     NaN
9993     NaN
Name: Discount, Length: 9994, dtype: float64

In [99]:
data['Discount'] = data['Discount'].replace(np.nan,0.00)

In [100]:
data['Discount']

0       0.00
1       0.00
2       0.00
3       0.45
4       0.20
        ...
9989    0.20
9990    0.00
9991    0.20
9992    0.00
9993    0.00
Name: Discount, Length: 9994, dtype: float64

In [101]:
#Replacinf the multiple values 
data.Segment.nunique()

3

In [102]:
data.Segment.unique()

array(['Consumer', 'Corporate', 'Home Office'], dtype=object)

In [103]:
data['Segment'].replace({'Consumer':'C','Corporate':'CO','Home Office':'HO'}) # replace the value of the segment

0        C
1        C
2       CO
3        C
4        C
        ..
9989     C
9990     C
9991     C
9992     C
9993     C
Name: Segment, Length: 9994, dtype: object

In [104]:
# if i want to save this change 
#data['Segment'] = data['Segment'].replace({'Consumer':'C','Corporate':'CO','Home Office':'HO'}) i need to run this code line

In [105]:
#replace using condition 
data['Quantity'].unique()

array([ 2,  3,  5,  7,  4,  6,  9,  1,  8, 14, 11, 13, 10, 12])

In [106]:
data['Quantity'].replace({1:'Low',2:'LOw',3:'Low',5:'high'}) # replacing some of the quality value to the low high ect

0        LOw
1        Low
2        LOw
3       high
4        LOw
        ...
9989     Low
9990     LOw
9991     LOw
9992       4
9993     LOw
Name: Quantity, Length: 9994, dtype: object

In [107]:
# Transforing the data 
# for single columns tranfromation 
data['Quantity'].map(lambda x:x*0.01)

0       0.02
1       0.03
2       0.02
3       0.05
4       0.02
        ...
9989    0.03
9990    0.02
9991    0.02
9992    0.04
9993    0.02
Name: Quantity, Length: 9994, dtype: float64

In [108]:
# for more flexible logic tarnformation 
data['Quantity'].apply(lambda x : 'high' if x>=4 else 'low') # better conditon for the dataset

0        low
1        low
2        low
3       high
4        low
        ...
9989     low
9990     low
9991     low
9992    high
9993     low
Name: Quantity, Length: 9994, dtype: object

In [109]:
# for entire dataste 
# data = data.applymap(lambda x : x.strip() if isinstance(x, str) else x) # the function use to remove the extra space form all the string value
# the version doesnot support the applymap() fucntion so i used only apply() or only map() function i.e.
data = data.apply(lambda x : x.strip() if isinstance(x, str) else x)

In [110]:
data.head(2)

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,2013,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2013-152156,2013,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [111]:
data.iloc[1:3,0:3]

   Row ID        Order ID  Year
1       2  CA-2013-152156  2013
2       3  CA-2013-138688  2013

In [112]:
data.loc[0:3, 'Order Date']

0   2013-11-09
1   2013-11-09
2   2013-06-13
3   2012-10-11
Name: Order Date, dtype: datetime64[ns]

In [113]:
data.loc[0:,'Order Date']

0      2013-11-09
1      2013-11-09
2      2013-06-13
3      2012-10-11
4      2012-10-11
          ...
9989   2011-01-22
9990   2014-02-27
9991   2014-02-27
9992   2014-02-27
9993   2014-05-05
Name: Order Date, Length: 9994, dtype: datetime64[ns]

# Aggregation and Meriging the data

In [114]:
data.head(4)

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,2013,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,2013,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,2013,2013-06-13,2013-06-17,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,2012,2012-10-11,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310

In [115]:
data.groupby('Category')['Profit'].sum()

Category
Furniture           18451.2728
Office Supplies    122490.8008
Technology         145454.9481
Name: Profit, dtype: float64

In [116]:
data.set_index('Order Date',inplace = True)

In [117]:
data.head(2)

,Row ID,Order ID,Year,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Order Date,,,,,,,,,,,,,,,,,,,,,
2013-11-09,1,CA-2013-152156,2013,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
2013-11-09,2,CA-2013-152156,2013,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [118]:
data.reset_index('Order Date',inplace = True)

In [119]:
data.head(2)

,Order Date,Row ID,Order ID,Year,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,2013-11-09,1,CA-2013-152156,2013,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2013-11-09,2,CA-2013-152156,2013,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [120]:
data.groupby(['Order Date','Region'])[['Profit','Sales']].sum() # group by multiple columns and  find the mulitple value

                       Profit     Sales
Order Date Region
2011-01-04 Central     5.5512    16.448
2011-01-05 Central   -65.9901   288.060
2011-01-06 East        4.8840    19.536
2011-01-07 South    1348.7212  4387.660
           West        9.3312    19.440
...                       ...       ...
2014-12-30 South     494.8649  1814.680
           West       45.9582   885.124
2014-12-31 Central    56.5110   209.300
           East       34.6365   466.842
           West       10.3890    37.648

[2956 rows x 2 columns]

In [121]:
d_R = data.groupby('Region')

In [122]:
d_R.Quantity.mean().sort_values(ascending = False) # in descending order

Region
South      3.832716
West       3.829535
Central    3.779595
East       3.728230
Name: Quantity, dtype: float64

In [123]:
d_R.Quantity.mean().sort_values() # in ascending order

Region
East       3.728230
Central    3.779595
West       3.829535
South      3.832716
Name: Quantity, dtype: float64

In [124]:
# find the maximum,minimum,mean,median, standard deviation of the Quantiy group by Region 
Quantity_describe = d_R.Quantity.agg(['max','min','mean','median','std'])

In [125]:
Quantity_describe.sort_values(by=Quantity_describe.columns[0], ascending=False)

         max  min      mean  median       std
Region
Central   14    1  3.779595     3.0  2.160561
East      14    1  3.728230     3.0  2.221779
South     14    1  3.832716     3.0  2.249379
West      14    1  3.829535     3.0  2.261270

# Merge and concatinate DataFrame

In [126]:
data_1 = pd.DataFrame({'X':list(range(9,90,9)),'Y':list(range(11,110,11)),'Z': list(range(10,100,10))})

In [127]:
data_1

    X   Y   Z
0   9  11  10
1  18  22  20
2  27  33  30
3  36  44  40
4  45  55  50
5  54  66  60
6  63  77  70
7  72  88  80
8  81  99  90

In [128]:
data_2 = pd.DataFrame({'A':list(range(12,120,12)),'B':list(range(13,130,13)),'C':list(range(14,140,14))})

In [129]:
data_2

     A    B    C
0   12   13   14
1   24   26   28
2   36   39   42
3   48   52   56
4   60   65   70
5   72   78   84
6   84   91   98
7   96  104  112
8  108  117  126

# Concat Dataframe : join vertically

In [130]:
data_con = pd.concat([data_1,data_2]) # join vertically 
data_con

      X     Y     Z      A      B      C
0   9.0  11.0  10.0    NaN    NaN    NaN
1  18.0  22.0  20.0    NaN    NaN    NaN
2  27.0  33.0  30.0    NaN    NaN    NaN
3  36.0  44.0  40.0    NaN    NaN    NaN
4  45.0  55.0  50.0    NaN    NaN    NaN
5  54.0  66.0  60.0    NaN    NaN    NaN
6  63.0  77.0  70.0    NaN    NaN    NaN
7  72.0  88.0  80.0    NaN    NaN    NaN
8  81.0  99.0  90.0    NaN    NaN    NaN
0   NaN   NaN   NaN   12.0   13.0   14.0
1   NaN   NaN   NaN   24.0   26.0   28.0
2   NaN   NaN   NaN   36.0   39.0   42.0
3   NaN   NaN   NaN   48.0   52.0   56.0
4   NaN   NaN   NaN   60.0   65.0   70.0
5   NaN   NaN   NaN   72.0   78.0   84.0
6   NaN   NaN   NaN   84.0   91.0   98.0
7   NaN   NaN   NaN   96.0  104.0  112.0
8   NaN   NaN   NaN  108.0  117.0  126.0

# Merge DataFrame :join Horizontally for this index most be same

In [131]:

data_merge = pd.merge(data_1,data_2,left_index = True ,right_index = True) #join horizontally 
data_merge

    X   Y   Z    A    B    C
0   9  11  10   12   13   14
1  18  22  20   24   26   28
2  27  33  30   36   39   42
3  36  44  40   48   52   56
4  45  55  50   60   65   70
5  54  66  60   72   78   84
6  63  77  70   84   91   98
7  72  88  80   96  104  112
8  81  99  90  108  117  126

In [132]:
data_n1 = pd.DataFrame({'X':list(range(9,90,9)),'Y':list(range(11,110,11)),'Z': list(range(10,100,10))})
data_n1

    X   Y   Z
0   9  11  10
1  18  22  20
2  27  33  30
3  36  44  40
4  45  55  50
5  54  66  60
6  63  77  70
7  72  88  80
8  81  99  90

In [133]:
data_n2 = pd.DataFrame({'A':list(range(8,80,4)),'B':list(range(10,100,5)),'C': list(range(12,120,6))})
data_n2

     A   B    C
0    8  10   12
1   12  15   18
2   16  20   24
3   20  25   30
4   24  30   36
5   28  35   42
6   32  40   48
7   36  45   54
8   40  50   60
9   44  55   66
10  48  60   72
11  52  65   78
12  56  70   84
13  60  75   90
14  64  80   96
15  68  85  102
16  72  90  108
17  76  95  114

In [134]:
data_merge1 = pd.merge(data_n1,data_n2,left_index = True,right_index = True) # merge operation 
data_merge1

    X   Y   Z   A   B   C
0   9  11  10   8  10  12
1  18  22  20  12  15  18
2  27  33  30  16  20  24
3  36  44  40  20  25  30
4  45  55  50  24  30  36
5  54  66  60  28  35  42
6  63  77  70  32  40  48
7  72  88  80  36  45  54
8  81  99  90  40  50  60

In [135]:
data_con1 = pd.concat([data_n1,data_n2],axis = 1) # add the two data frame in by using concat 
data_con1

       X     Y     Z   A   B    C
0    9.0  11.0  10.0   8  10   12
1   18.0  22.0  20.0  12  15   18
2   27.0  33.0  30.0  16  20   24
3   36.0  44.0  40.0  20  25   30
4   45.0  55.0  50.0  24  30   36
5   54.0  66.0  60.0  28  35   42
6   63.0  77.0  70.0  32  40   48
7   72.0  88.0  80.0  36  45   54
8   81.0  99.0  90.0  40  50   60
9    NaN   NaN   NaN  44  55   66
10   NaN   NaN   NaN  48  60   72
11   NaN   NaN   NaN  52  65   78
12   NaN   NaN   NaN  56  70   84
13   NaN   NaN   NaN  60  75   90
14   NaN   NaN   NaN  64  80   96
15   NaN   NaN   NaN  68  85  102
16   NaN   NaN   NaN  72  90  108
17   NaN   NaN   NaN  76  95  114

# set and Reset index on pandas

In [136]:
data_n1

    X   Y   Z
0   9  11  10
1  18  22  20
2  27  33  30
3  36  44  40
4  45  55  50
5  54  66  60
6  63  77  70
7  72  88  80
8  81  99  90

In [137]:
data_n1.set_index('X',inplace = True) # set the X as index

In [139]:

data_n1

     Y   Z
X
9   11  10
18  22  20
27  33  30
36  44  40
45  55  50
54  66  60
63  77  70
72  88  80
81  99  90

In [142]:
data_n1.reset_index(inplace = True ) # reset the index

In [143]:
data_n1

    X   Y   Z
0   9  11  10
1  18  22  20
2  27  33  30
3  36  44  40
4  45  55  50
5  54  66  60
6  63  77  70
7  72  88  80
8  81  99  90

In [148]:
data_n1.set_index(['X','Y'],inplace = True) # set multiple columns as index

In [149]:
data_n1

        Z
X  Y
9  11  10
18 22  20
27 33  30
36 44  40
45 55  50
54 66  60
63 77  70
72 88  80
81 99  90

In [146]:
data_n1.reset_index(inplace = True)

In [147]:
data_n1

    X   Y   Z
0   9  11  10
1  18  22  20
2  27  33  30
3  36  44  40
4  45  55  50
5  54  66  60
6  63  77  70
7  72  88  80
8  81  99  90

# load dataset

In [185]:
cars_data = pd.read_csv(r'cars_data_updated - cars_data_updated (1).csv')

In [186]:
cars_data.head(2)

,location,year,run,fuel_type,trans,owner,mileage,engine,power,seats,new_price,price,brand,model,@
0,location,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,NaN,1.75,Maruti,Wagon,NaN
1,location,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,NaN,12.50,Hyundai,Creta,NaN

In [187]:
cars_data['location'].unique()

array(['location', 'Chennai', 'Coimbatore', 'Hyderabad', 'Jaipur',
       'Mumbai', 'Pune', 'Kochi', 'Kolkata', 'Delhi', 'Bangalore',
       'Ahmedabad'], dtype=object)

In [188]:
#select all data from mumbai 
# data_m = cars_data[cars_data['location']== 'Mumbai']
# data_m
# or
con = cars_data['location']== 'Mumbai'
cars_data[con]

,location,year,run,fuel_type,trans,owner,mileage,engine,power,seats,new_price,price,brand,model,@
7,Mumbai,2016,36000,Diesel,Automatic,First,11.36,2755.0,171.50,8.0,21 Lakh,17.50,Toyota,Innova,NaN
22,Mumbai,2015,55985,Petrol,Automatic,First,13.53,1984.0,177.01,5.0,NaN,23.50,Audi,A6,NaN
25,Mumbai,2012,51920,Petrol,Manual,First,16.80,1497.0,116.30,5.0,NaN,4.25,Honda,City,NaN
29,Mumbai,2007,262000,Diesel,Manual,Fourth & Above,12.80,2494.0,102.00,7.0,NaN,4.00,Toyota,Innova,NaN
45,Mumbai,2016,52001,Petrol,Automatic,First,14.28,1798.0,138.03,5.0,NaN,10.11,Toyota,Corolla,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7185,Mumbai,2015,31293,Petrol,Manual,First,18.60,1197.0,81.83,5.0,NaN,NaN,Hyundai,i20,NaN
7218,Mumbai,2018,3800,Diesel,Automatic,First,24.30,1248.0,88.50,5.0,12.46 Lakh,NaN,Maruti,Vitara,NaN
7229,Mumbai,2011,67500,Petrol,Automatic,Second,14.40,1598.0,103.60,5.0,NaN,NaN,Volkswagen,Vento,NaN
7232,Mumbai,2018,6000,Petrol,Manual,First,16.00,1368.0,160.00,5.0,18.16 Lakh,NaN,Jeep,Compass,NaN
7249,Mumbai,2015,59000,Petrol,Automatic,First,17.21,1197.0,103.60,5.0,NaN,NaN,Volkswagen,Polo,NaN

In [189]:
data_il = cars_data.set_index('location') #set location as index

In [190]:
data_il

,year,run,fuel_type,trans,owner,mileage,engine,power,seats,new_price,price,brand,model,@
location,,,,,,,,,,,,,,
location,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,NaN,1.75,Maruti,Wagon,NaN
location,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,NaN,12.50,Hyundai,Creta,NaN
Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,8.61 Lakh,4.50,Honda,Jazz,NaN
Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,NaN,6.00,Maruti,Ertiga,NaN
Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,NaN,17.74,Audi,A4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Hyderabad,2011,89411,Diesel,Manual,First,20.54,1598.0,103.60,5.0,NaN,NaN,Volkswagen,Vento,NaN
Mumbai,2015,59000,Petrol,Automatic,First,17.21,1197.0,103.60,5.0,NaN,NaN,Volkswagen,Polo,NaN
Kolkata,2012,28000,Diesel,Manual,First,23.08,1461.0,63.10,5.0,NaN,NaN,Nissan,Micra,NaN
Pune,2013,52262,Petrol,Automatic,Third,17.20,1197.0,103.60,5.0,NaN,NaN,Volkswagen,Polo,NaN
Kochi,2014,72443,Diesel,Automatic,First,10.00,2148.0,170.00,5.0,NaN,NaN,Mercedes-Benz,E-Class,NaN

In [191]:
data_il.loc['Mumbai'] #select all the data where location = Mumbai

,year,run,fuel_type,trans,owner,mileage,engine,power,seats,new_price,price,brand,model,@
location,,,,,,,,,,,,,,
Mumbai,2016,36000,Diesel,Automatic,First,11.36,2755.0,171.50,8.0,21 Lakh,17.50,Toyota,Innova,NaN
Mumbai,2015,55985,Petrol,Automatic,First,13.53,1984.0,177.01,5.0,NaN,23.50,Audi,A6,NaN
Mumbai,2012,51920,Petrol,Manual,First,16.80,1497.0,116.30,5.0,NaN,4.25,Honda,City,NaN
Mumbai,2007,262000,Diesel,Manual,Fourth & Above,12.80,2494.0,102.00,7.0,NaN,4.00,Toyota,Innova,NaN
Mumbai,2016,52001,Petrol,Automatic,First,14.28,1798.0,138.03,5.0,NaN,10.11,Toyota,Corolla,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mumbai,2015,31293,Petrol,Manual,First,18.60,1197.0,81.83,5.0,NaN,NaN,Hyundai,i20,NaN
Mumbai,2018,3800,Diesel,Automatic,First,24.30,1248.0,88.50,5.0,12.46 Lakh,NaN,Maruti,Vitara,NaN
Mumbai,2011,67500,Petrol,Automatic,Second,14.40,1598.0,103.60,5.0,NaN,NaN,Volkswagen,Vento,NaN
Mumbai,2018,6000,Petrol,Manual,First,16.00,1368.0,160.00,5.0,18.16 Lakh,NaN,Jeep,Compass,NaN
Mumbai,2015,59000,Petrol,Automatic,First,17.21,1197.0,103.60,5.0,NaN,NaN,Volkswagen,Polo,NaN

In [192]:
#set location and fule type as index 
data_lf = cars_data.set_index(['location','fuel_type'])

In [193]:
data_lf

                      year    run      trans   owner  mileage  engine   power  \
location   fuel_type
location   CNG        2010  72000     Manual   First    26.60   998.0   58.16
           Diesel     2015  41000     Manual   First    19.67  1582.0  126.20
Chennai    Petrol     2011  46000     Manual   First    18.20  1199.0   88.70
           Diesel     2012  87000     Manual   First    20.77  1248.0   88.76
Coimbatore Diesel     2013  40670  Automatic  Second    15.20  1968.0  140.80
...                    ...    ...        ...     ...      ...     ...     ...
Hyderabad  Diesel     2011  89411     Manual   First    20.54  1598.0  103.60
Mumbai     Petrol     2015  59000  Automatic   First    17.21  1197.0  103.60
Kolkata    Diesel     2012  28000     Manual   First    23.08  1461.0   63.10
Pune       Petrol     2013  52262  Automatic   Third    17.20  1197.0  103.60
Kochi      Diesel     2014  72443  Automatic   First    10.00  2148.0  170.00

                      seats  new_price  price          brand    model   @
location   fuel_type
location   CNG          5.0        NaN   1.75         Maruti    Wagon NaN
           Diesel       5.0        NaN  12.50        Hyundai    Creta NaN
Chennai    Petrol       5.0  8.61 Lakh   4.50          Honda     Jazz NaN
           Diesel       7.0        NaN   6.00         Maruti   Ertiga NaN
Coimbatore Diesel       5.0        NaN  17.74           Audi       A4 NaN
...                     ...        ...    ...            ...      ...  ..
Hyderabad  Diesel       5.0        NaN    NaN     Volkswagen    Vento NaN
Mumbai     Petrol       5.0        NaN    NaN     Volkswagen     Polo NaN
Kolkata    Diesel       5.0        NaN    NaN         Nissan    Micra NaN
Pune       Petrol       5.0        NaN    NaN     Volkswagen     Polo NaN
Kochi      Diesel       5.0        NaN    NaN  Mercedes-Benz  E-Class NaN

[7253 rows x 13 columns]

In [194]:
data_lf.loc['Pune','Petrol']
#also
# con1 = cars_data['location']='Pune'
# con2 = cars_data['fuel_type']='Petrol'
# cars_data[con1 & con2]

/var/folders/gk/8p2cy2r906j11_0stbnxqlb40000gn/T/ipykernel_8344/2604847065.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  data_lf.loc['Pune','Petrol']

                    year    run      trans   owner  mileage  engine   power  \
location fuel_type
Pune     Petrol     2017  70000     Manual   First    17.57  1193.0   88.70
         Petrol     2009  95980     Manual   First    20.36  1197.0   78.90
         Petrol     2017  32851     Manual   First    19.83  1198.0   67.00
         Petrol     2009  66000     Manual  Second    17.00  1197.0   80.00
         Petrol     2011  43874     Manual   First    18.90   998.0   67.10
...                  ...    ...        ...     ...      ...     ...     ...
         Petrol     2004  43000     Manual  Second    15.40  1590.0   94.00
         Petrol     2011  30000     Manual   First    19.81  1086.0   68.05
         Petrol     2014  30315     Manual   First    18.60  1197.0   81.83
         Petrol     2009  45463     Manual   First    14.49  1399.0   92.70
         Petrol     2013  52262  Automatic   Third    17.20  1197.0  103.60

                    seats  new_price  price       brand   model   @
location fuel_type
Pune     Petrol       5.0  6.67 Lakh   4.50        Tata    Zest NaN
         Petrol       5.0        NaN   2.25     Hyundai     i10 NaN
         Petrol       7.0  6.45 Lakh   3.95      Datsun      GO NaN
         Petrol       5.0        NaN   2.70     Hyundai     i20 NaN
         Petrol       5.0        NaN   2.45      Maruti   Wagon NaN
...                   ...        ...    ...         ...     ...  ..
         Petrol       5.0        NaN    NaN      Maruti  Baleno NaN
         Petrol       5.0        NaN    NaN     Hyundai     i10 NaN
         Petrol       5.0        NaN    NaN     Hyundai     i20 NaN
         Petrol       5.0        NaN    NaN   Chevrolet    Aveo NaN
         Petrol       5.0        NaN    NaN  Volkswagen    Polo NaN

[387 rows x 13 columns]

# Group By

In [195]:
cars_data.head(2)

,location,year,run,fuel_type,trans,owner,mileage,engine,power,seats,new_price,price,brand,model,@
0,location,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,NaN,1.75,Maruti,Wagon,NaN
1,location,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,NaN,12.50,Hyundai,Creta,NaN

In [196]:
cars_data.columns

Index(['location', 'year', 'run', 'fuel_type', 'trans', 'owner', 'mileage',
       'engine', 'power', 'seats', 'new_price', 'price', 'brand', 'model',
       '@'],
      dtype='object')

In [197]:
# find the min,max,sum,mean,median,std of mileage and power group by location and brand

new_data_cars = cars_data.groupby(['location','brand'])[['mileage','power']].agg(['mean','std','sum','median','min','max']).reset_index()

In [198]:
new_data_cars

      location       brand    mileage                                         \
                                 mean       std     sum median    min    max
0    Ahmedabad        Audi  14.991538  3.335238  194.89  16.55   9.74  20.38
1    Ahmedabad         BMW  19.118333  3.170885  344.13  18.68  11.50  22.69
2    Ahmedabad   Chevrolet  18.033333  0.208167   54.10  18.10  17.80  18.20
3    Ahmedabad        Ford  21.583333  1.744037  129.50  21.50  20.00  23.50
4    Ahmedabad       Honda  19.823529  6.379658  674.00  18.70   0.00  27.30
..         ...         ...        ...       ...     ...    ...    ...    ...
258       Pune      Toyota  14.481475  4.219345  883.37  12.99   0.00  23.59
259       Pune  Volkswagen  17.520227  2.743884  770.89  16.47  14.40  22.07
260       Pune       Volvo  18.400000  6.929646   36.80  18.40  13.50  23.30
261   location     Hyundai  19.670000       NaN   19.67  19.67  19.67  19.67
262   location      Maruti  26.600000       NaN   26.60  26.60  26.60  26.60

          power
           mean        std      sum  median     min     max
0    181.136154  37.382124  2354.77  181.00  140.00  241.38
1    196.190556  30.477428  3531.43  190.00  177.00  308.43
2     99.500000  41.942461   298.50   76.80   73.80  147.90
3     81.986667  15.667049   491.92   79.00   68.00   98.96
4    107.990909  19.884909  3563.70   98.60   86.70  177.60
..          ...        ...      ...     ...     ...     ...
258  122.745789  35.830399  6996.51  102.00   67.04  174.50
259   96.130227  20.561102  4229.73  103.60   73.75  167.70
260  182.500000  45.961941   365.00  182.50  150.00  215.00
261  126.200000        NaN   126.20  126.20  126.20  126.20
262   58.160000        NaN    58.16   58.16   58.16   58.16

[263 rows x 14 columns]

In [200]:
# find the min,sum,max for mileage and mean,std,median power group by location and brand
new_data_cars = cars_data.groupby(['location','brand'])[['mileage','power']].agg({
    'mileage':['min','max','sum'],'power':['mean','std','median']
}).reset_index()

In [201]:
new_data_cars

      location       brand mileage                      power             \
                               min    max     sum        mean        std
0    Ahmedabad        Audi    9.74  20.38  194.89  181.136154  37.382124
1    Ahmedabad         BMW   11.50  22.69  344.13  196.190556  30.477428
2    Ahmedabad   Chevrolet   17.80  18.20   54.10   99.500000  41.942461
3    Ahmedabad        Ford   20.00  23.50  129.50   81.986667  15.667049
4    Ahmedabad       Honda    0.00  27.30  674.00  107.990909  19.884909
..         ...         ...     ...    ...     ...         ...        ...
258       Pune      Toyota    0.00  23.59  883.37  122.745789  35.830399
259       Pune  Volkswagen   14.40  22.07  770.89   96.130227  20.561102
260       Pune       Volvo   13.50  23.30   36.80  182.500000  45.961941
261   location     Hyundai   19.67  19.67   19.67  126.200000        NaN
262   location      Maruti   26.60  26.60   26.60   58.160000        NaN


     median
0    181.00
1    190.00
2     76.80
3     79.00
4     98.60
..      ...
258  102.00
259  103.60
260  182.50
261  126.20
262   58.16

[263 rows x 8 columns]