In [345]:
!pip install pandas

Requirement already satisfied: pandas in ./venv/lib/python3.13/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in ./venv/lib/python3.13/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1
[notice] To update, run: pip install --upgrade pip

In [346]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [347]:
#Data Structure in pandas
# series

In [348]:
l = list(range(0,10,2))

In [349]:
df1 = pd.Series(l)
df1

0    0
1    2
2    4
3    6
4    8
dtype: int64

In [350]:
df2 = pd.DataFrame(l,columns = ['values'])
df2

   values
0       0
1       2
2       4
3       6
4       8

In [351]:
df2.columns

Index(['values'], dtype='str')

In [352]:
df2.head()

   values
0       0
1       2
2       4
3       6
4       8

In [353]:
df2.head(2)

   values
0       0
1       2

In [354]:
df2.tail()

   values
0       0
1       2
2       4
3       6
4       8

In [355]:
df2.tail(2)

   values
3       6
4       8

In [356]:
df2.info

<bound method DataFrame.info of    values
0       0
1       2
2       4
3       6
4       8>

In [357]:
df2.describe()

         values
count  5.000000
mean   4.000000
std    3.162278
min    0.000000
25%    2.000000
50%    4.000000
75%    6.000000
max    8.000000

In [358]:
df2.size

5

In [359]:
data = {
    'prompts':['explain AI','Write_code','Summerize'],
    'token':[150,300,280],
    'model':['GPT-4','GPT-4','Cloud']
}
df = pd.DataFrame(data)

In [360]:
df

      prompts  token  model
0  explain AI    150  GPT-4
1  Write_code    300  GPT-4
2   Summerize    280  Cloud

In [361]:
df.head(2)

      prompts  token  model
0  explain AI    150  GPT-4
1  Write_code    300  GPT-4

In [362]:
df.tail(1)

     prompts  token  model
2  Summerize    280  Cloud

In [363]:
df.describe()

            token
count    3.000000
mean   243.333333
std     81.445278
min    150.000000
25%    215.000000
50%    280.000000
75%    290.000000
max    300.000000

In [364]:
!pip install openpyxl

Requirement already satisfied: openpyxl in ./venv/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in ./venv/lib/python3.13/site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1
[notice] To update, run: pip install --upgrade pip

In [365]:
df1 = pd.read_excel('/Users/sanjaymagar/Desktop/Ecommerce Sales Analysis.xlsx')

In [366]:
df1.head(2)

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,2013,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2013-152156,2013,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [367]:
df.to_csv('llm usage.csv',index=False)

In [368]:
load = pd.read_csv('llm usage.csv')
load

      prompts  token  model
0  explain AI    150  GPT-4
1  Write_code    300  GPT-4
2   Summerize    280  Cloud

# get  data set from kagle

In [369]:
data_k = pd.read_csv(r'/Users/sanjaymagar/Desktop/Cleaned_HR_Data_Analysis.csv')
data_k.head(2)

,Employee ID,StartDate,Title,BusinessUnit,EmployeeStatus,EmployeeType,PayZone,EmployeeClassificationType,DepartmentType,Division,...,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Training Duration(Days),Training Cost,Age
0,3427,20-Sep-19,Production Technician I,CCDR,Active,Contract,Zone C,Temporary,Production,Finance & Accounting,...,1,2,3,15-Jul-23,Leadership Development,Internal,Failed,2,606.11,50
1,3428,11-Feb-23,Production Technician I,EW,Active,Contract,Zone A,Part-Time,Production,Aerial,...,2,1,5,12-Sep-22,Customer Service,External,Incomplete,4,673.02,58

In [370]:
data_k.columns

Index(['Employee ID', 'StartDate', 'Title', 'BusinessUnit', 'EmployeeStatus',
       'EmployeeType', 'PayZone', 'EmployeeClassificationType',
       'DepartmentType', 'Division', 'DOB', 'State', 'GenderCode', 'RaceDesc',
       'MaritalDesc', 'Performance Score', 'Current Employee Rating',
       'Survey Date', 'Engagement Score', 'Satisfaction Score',
       'Work-Life Balance Score', 'Training Date', 'Training Program Name',
       'Training Type', 'Training Outcome', 'Training Duration(Days)',
       'Training Cost', 'Age'],
      dtype='str')

In [371]:
data_k.describe()

,Employee ID,Current Employee Rating,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Duration(Days),Training Cost,Age
count,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000
mean,2470.591916,2.974692,2.941652,3.028471,2.989104,2.973989,559.278956,49.448506
std,859.450107,1.012610,1.435230,1.410067,1.408816,1.419682,263.333611,17.689179
min,1001.000000,1.000000,1.000000,1.000000,1.000000,1.000000,100.040000,17.000000
25%,1736.000000,2.000000,2.000000,2.000000,2.000000,2.000000,328.060000,34.000000
50%,2456.000000,3.000000,3.000000,3.000000,3.000000,3.000000,571.810000,49.000000
75%,3197.000000,3.000000,4.000000,4.000000,4.000000,4.000000,788.330000,65.000000
max,4000.000000,5.000000,5.000000,5.000000,5.000000,5.000000,999.970000,82.000000

In [372]:
data_k.isna().sum()

Employee ID                   0
StartDate                     0
Title                         0
BusinessUnit                  0
EmployeeStatus                0
EmployeeType                  0
PayZone                       0
EmployeeClassificationType    0
DepartmentType                0
Division                      0
DOB                           0
State                         0
GenderCode                    0
RaceDesc                      0
MaritalDesc                   0
Performance Score             0
Current Employee Rating       0
Survey Date                   0
Engagement Score              0
Satisfaction Score            0
Work-Life Balance Score       0
Training Date                 0
Training Program Name         0
Training Type                 0
Training Outcome              0
Training Duration(Days)       0
Training Cost                 0
Age                           0
dtype: int64

In [373]:
data_k.tail(2)

,Employee ID,StartDate,Title,BusinessUnit,EmployeeStatus,EmployeeType,PayZone,EmployeeClassificationType,DepartmentType,Division,...,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Training Duration(Days),Training Cost,Age
2843,3425,28-May-19,Production Technician I,WBL,Terminated,Contract,Zone B,Full-Time,Production,Aerial,...,5,2,3,19-May-23,Technical Skills,External,Completed,3,184.27,65
2844,3426,27-Apr-22,Production Technician I,BPC,Active,Full-Time,Zone B,Temporary,Production,Field Operations,...,1,3,2,02-May-23,Leadership Development,Internal,Failed,5,675.37,32

In [374]:
data_k['Engagement Score']

0       1
1       2
2       1
3       5
4       2
       ..
2840    5
2841    4
2842    2
2843    5
2844    1
Name: Engagement Score, Length: 2845, dtype: int64

In [375]:
cond1 = data_k['Engagement Score']<5
cond2 = data_k['Age']>50

In [376]:
data_k['Age']

0       50
1       58
2       27
3       23
4       50
        ..
2840    63
2841    19
2842    23
2843    65
2844    32
Name: Age, Length: 2845, dtype: int64

In [377]:
#And condition 
data_a  = data_k[cond1 & cond2]
data_a.head(5)

,Employee ID,StartDate,Title,BusinessUnit,EmployeeStatus,EmployeeType,PayZone,EmployeeClassificationType,DepartmentType,Division,...,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Training Duration(Days),Training Cost,Age
1,3428,11-Feb-23,Production Technician I,EW,Active,Contract,Zone A,Part-Time,Production,Aerial,...,2,1,5,12-Sep-22,Customer Service,External,Incomplete,4,673.02,58
5,3432,17-Jan-20,Area Sales Manager,BPC,Active,Contract,Zone B,Full-Time,Sales,Field Operations,...,2,3,5,18-Apr-23,Project Management,Internal,Passed,2,820.33,71
6,3433,06-Apr-22,Area Sales Manager,WBL,Active,Full-Time,Zone B,Temporary,Sales,General - Eng,...,1,5,2,06-Aug-22,Customer Service,External,Passed,5,295.08,80
7,3434,06-Nov-20,Area Sales Manager,CCDR,Active,Contract,Zone C,Full-Time,Sales,Engineers,...,1,4,2,07-Oct-22,Leadership Development,Internal,Passed,3,790.15,63
10,3437,04-Aug-23,Area Sales Manager,SVG,Active,Contract,Zone B,Temporary,Sales,Field Operations,...,3,2,5,20-Oct-22,Technical Skills,Internal,Failed,1,455.68,59

In [378]:
# Or condition 
data_o = data_k[cond1 | cond2]
data_o.head(5)

,Employee ID,StartDate,Title,BusinessUnit,EmployeeStatus,EmployeeType,PayZone,EmployeeClassificationType,DepartmentType,Division,...,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Training Duration(Days),Training Cost,Age
0,3427,20-Sep-19,Production Technician I,CCDR,Active,Contract,Zone C,Temporary,Production,Finance & Accounting,...,1,2,3,15-Jul-23,Leadership Development,Internal,Failed,2,606.11,50
1,3428,11-Feb-23,Production Technician I,EW,Active,Contract,Zone A,Part-Time,Production,Aerial,...,2,1,5,12-Sep-22,Customer Service,External,Incomplete,4,673.02,58
2,3429,10-Dec-18,Area Sales Manager,PL,Active,Full-Time,Zone B,Part-Time,Sales,General - Sga,...,1,2,1,13-Aug-22,Leadership Development,External,Failed,2,413.28,27
4,3431,29-Jun-19,Area Sales Manager,TNS,Active,Contract,Zone A,Temporary,Sales,General - Con,...,2,5,3,13-Jul-23,Technical Skills,External,Failed,5,399.03,50
5,3432,17-Jan-20,Area Sales Manager,BPC,Active,Contract,Zone B,Full-Time,Sales,Field Operations,...,2,3,5,18-Apr-23,Project Management,Internal,Passed,2,820.33,71

In [379]:
# isin 
data_k['EmployeeClassificationType'].unique()

<StringArray>
['Temporary', 'Part-Time', 'Full-Time']
Length: 3, dtype: str

In [380]:
con = ['Temporary', 'Part-Time']

In [381]:
data_k[data_k['EmployeeClassificationType'].isin(con)].head(5)

,Employee ID,StartDate,Title,BusinessUnit,EmployeeStatus,EmployeeType,PayZone,EmployeeClassificationType,DepartmentType,Division,...,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Training Duration(Days),Training Cost,Age
0,3427,20-Sep-19,Production Technician I,CCDR,Active,Contract,Zone C,Temporary,Production,Finance & Accounting,...,1,2,3,15-Jul-23,Leadership Development,Internal,Failed,2,606.11,50
1,3428,11-Feb-23,Production Technician I,EW,Active,Contract,Zone A,Part-Time,Production,Aerial,...,2,1,5,12-Sep-22,Customer Service,External,Incomplete,4,673.02,58
2,3429,10-Dec-18,Area Sales Manager,PL,Active,Full-Time,Zone B,Part-Time,Sales,General - Sga,...,1,2,1,13-Aug-22,Leadership Development,External,Failed,2,413.28,27
4,3431,29-Jun-19,Area Sales Manager,TNS,Active,Contract,Zone A,Temporary,Sales,General - Con,...,2,5,3,13-Jul-23,Technical Skills,External,Failed,5,399.03,50
6,3433,06-Apr-22,Area Sales Manager,WBL,Active,Full-Time,Zone B,Temporary,Sales,General - Eng,...,1,5,2,06-Aug-22,Customer Service,External,Passed,5,295.08,80

In [382]:
# not is in 
data_k[~data_k['EmployeeClassificationType'].isin(con)].head(5)

,Employee ID,StartDate,Title,BusinessUnit,EmployeeStatus,EmployeeType,PayZone,EmployeeClassificationType,DepartmentType,Division,...,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Training Duration(Days),Training Cost,Age
3,3430,21-Jun-21,Area Sales Manager,CCDR,Active,Contract,Zone A,Full-Time,Sales,Finance & Accounting,...,5,5,4,15-Dec-22,Project Management,External,Completed,3,663.78,23
5,3432,17-Jan-20,Area Sales Manager,BPC,Active,Contract,Zone B,Full-Time,Sales,Field Operations,...,2,3,5,18-Apr-23,Project Management,Internal,Passed,2,820.33,71
7,3434,06-Nov-20,Area Sales Manager,CCDR,Active,Contract,Zone C,Full-Time,Sales,Engineers,...,1,4,2,07-Oct-22,Leadership Development,Internal,Passed,3,790.15,63
13,3440,05-Dec-19,Area Sales Manager,CCDR,Active,Contract,Zone A,Full-Time,Sales,Finance & Accounting,...,1,4,5,29-May-23,Communication Skills,External,Failed,1,649.03,68
15,3442,09-Jul-19,Area Sales Manager,PYZ,Active,Full-Time,Zone A,Full-Time,IT/IS,Field Operations,...,2,5,3,06-Mar-23,Project Management,External,Failed,4,286.87,67

In [383]:
data_k.loc[1:10,['Employee ID','Title']]

    Employee ID                    Title
1          3428  Production Technician I
2          3429       Area Sales Manager
3          3430       Area Sales Manager
4          3431       Area Sales Manager
5          3432       Area Sales Manager
6          3433       Area Sales Manager
7          3434       Area Sales Manager
8          3435       Area Sales Manager
9          3436       Area Sales Manager
10         3437       Area Sales Manager

In [384]:
data_k.iloc[0:5,3:5]

  BusinessUnit EmployeeStatus
0         CCDR         Active
1           EW         Active
2           PL         Active
3         CCDR         Active
4          TNS         Active

In [385]:
sdata = data_k['Satisfaction Score']
sdata.head()

0    2
1    1
2    2
3    5
4    5
Name: Satisfaction Score, dtype: int64

In [386]:
sdata.value_counts()

Satisfaction Score
4    612
3    569
5    565
1    562
2    537
Name: count, dtype: int64

In [387]:
sdata.unique()

array([2, 1, 5, 3, 4])

In [388]:
sdata.nunique()

5

In [389]:
sdata.mean()

np.float64(3.0284710017574694)

In [390]:
sdata.median()

np.float64(3.0)

In [391]:
sdata.sort_values()

1379    1
478     1
2316    1
2315    1
1776    1
       ..
2099    5
2101    5
688     5
2106    5
1422    5
Name: Satisfaction Score, Length: 2845, dtype: int64

In [392]:
sdata.quantile(0.5)

np.float64(3.0)

In [393]:
sdata.quantile(0.75)

np.float64(4.0)

In [394]:
sdata.quantile(0.25)

np.float64(2.0)

In [395]:
data_k.sort_values(by=['Age'])

,Employee ID,StartDate,Title,BusinessUnit,EmployeeStatus,EmployeeType,PayZone,EmployeeClassificationType,DepartmentType,Division,...,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Training Duration(Days),Training Cost,Age
1518,2038,02-Sep-18,Production Technician I,MSC,Active,Part-Time,Zone A,Temporary,Production,Splicing,...,5,3,2,13-Aug-22,Technical Skills,Internal,Passed,2,694.03,17
1228,1743,30-Nov-18,Production Technician I,SVG,Active,Full-Time,Zone C,Temporary,Production,Splicing,...,4,1,5,13-Jul-23,Project Management,External,Passed,4,954.37,17
2622,3176,13-Dec-18,Production Technician I,SVG,Active,Full-Time,Zone A,Full-Time,Production,Project Management - Con,...,5,3,5,24-Jan-23,Leadership Development,External,Passed,5,638.26,18
2260,2786,29-Dec-18,Production Technician II,PYZ,Active,Contract,Zone A,Full-Time,Production,Field Operations,...,4,3,1,16-Jun-23,Communication Skills,External,Incomplete,4,485.05,18
636,1127,26-Feb-19,Production Technician II,PL,Active,Full-Time,Zone A,Full-Time,Production,General - Con,...,5,1,3,04-Sep-22,Communication Skills,External,Incomplete,2,500.83,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1539,2060,26-Jan-23,Production Technician I,BPC,Active,Part-Time,Zone C,Part-Time,Production,Field Operations,...,5,5,5,23-Jul-23,Project Management,External,Failed,3,442.39,81
974,1474,01-Feb-23,Production Technician II,MSC,Terminated,Full-Time,Zone C,Part-Time,Production,Engineers,...,2,1,3,19-Feb-23,Project Management,External,Failed,1,798.37,81
2755,3326,14-Jan-22,Production Technician I,PYZ,Active,Contract,Zone A,Temporary,Production,General - Con,...,4,1,3,06-Nov-22,Project Management,Internal,Completed,3,115.27,81
1569,2090,12-Jan-23,Production Technician II,EW,Active,Part-Time,Zone B,Full-Time,Production,General - Sga,...,3,4,3,23-Oct-22,Leadership Development,Internal,Incomplete,1,189.64,81
604,1095,07-Apr-23,Production Technician II,WBL,Active,Full-Time,Zone A,Temporary,Production,Engineers,...,1,2,1,17-Aug-22,Customer Service,Internal,Passed,4,715.87,82

# Data cleaning with pandas

In [396]:
# rename the column 
data_k.rename(columns = {'Age':'Umer'},inplace = True)
data_k.head(2)

,Employee ID,StartDate,Title,BusinessUnit,EmployeeStatus,EmployeeType,PayZone,EmployeeClassificationType,DepartmentType,Division,...,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Training Duration(Days),Training Cost,Umer
0,3427,20-Sep-19,Production Technician I,CCDR,Active,Contract,Zone C,Temporary,Production,Finance & Accounting,...,1,2,3,15-Jul-23,Leadership Development,Internal,Failed,2,606.11,50
1,3428,11-Feb-23,Production Technician I,EW,Active,Contract,Zone A,Part-Time,Production,Aerial,...,2,1,5,12-Sep-22,Customer Service,External,Incomplete,4,673.02,58

In [397]:
data_k.rename(columns = {'Training Duration(Days)':'Training duration(day)','Training Cost':'training cost'},inplace = True)
data_k.head(2)

,Employee ID,StartDate,Title,BusinessUnit,EmployeeStatus,EmployeeType,PayZone,EmployeeClassificationType,DepartmentType,Division,...,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Training duration(day),training cost,Umer
0,3427,20-Sep-19,Production Technician I,CCDR,Active,Contract,Zone C,Temporary,Production,Finance & Accounting,...,1,2,3,15-Jul-23,Leadership Development,Internal,Failed,2,606.11,50
1,3428,11-Feb-23,Production Technician I,EW,Active,Contract,Zone A,Part-Time,Production,Aerial,...,2,1,5,12-Sep-22,Customer Service,External,Incomplete,4,673.02,58

In [398]:
data_k.rename(columns = {'Umer':'Age'},inplace = True)
data_k.head(1)

,Employee ID,StartDate,Title,BusinessUnit,EmployeeStatus,EmployeeType,PayZone,EmployeeClassificationType,DepartmentType,Division,...,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Training duration(day),training cost,Age
0,3427,20-Sep-19,Production Technician I,CCDR,Active,Contract,Zone C,Temporary,Production,Finance & Accounting,...,1,2,3,15-Jul-23,Leadership Development,Internal,Failed,2,606.11,50

In [399]:
#load the unclened data set 
data_u = pd.read_csv(r"/Users/sanjaymagar/Desktop/Messy_HR_Dataset_Detailed.csv")

In [400]:
df1 = data_u.copy()
df1.head(4)

,Unnamed: 0,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Satisfaction Score,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Location,Trainer,Training Duration(Days),Training Cost
0,0,Uriah,Bridges,20-Sep-19,NaN,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,...,2,3,15-Jul-23,Leadership Development,Internal,Failed,South Marisa,Taylor Rodriguez,2,606.11
1,1,Paula,Small,11-Feb-23,NaN,Production Technician I,Renee Mccormick,paula.small@bilearner.com,EW,Active,...,1,5,12-Sep-22,Customer Service,External,Incomplete,Tammieville,Kelly Patterson DDS,4,673.02
2,2,Edward,Buck,10-Dec-18,NaN,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,...,2,1,13-Aug-22,Leadership Development,External,Failed,East Roberthaven,Taylor Thomas,2,413.28
3,3,Michael,Riordan,21-Jun-21,NaN,Area Sales Manager,Rebekah Wright,michael.riordan@bilearner.com,CCDR,Active,...,5,4,15-Dec-22,Project Management,External,Completed,Garzatown,Holly Elliott,3,663.78

In [401]:
df1.isna().sum()

Unnamed: 0                       0
FirstName                        0
LastName                         0
StartDate                        0
ExitDate                      1544
Title                            0
Supervisor                       0
ADEmail                          0
BusinessUnit                     0
EmployeeStatus                   0
EmployeeType                     0
PayZone                          0
EmployeeClassificationType       0
TerminationType                  0
TerminationDescription        1544
DepartmentType                   0
Division                         0
DOB                              0
State                            0
JobFunctionDescription           0
GenderCode                       0
LocationCode                     0
RaceDesc                         0
MaritalDesc                      0
Performance Score                0
Current Employee Rating          0
Employee ID                      0
Survey Date                      0
Engagement Score                 0
Satisfaction Score               0
Work-Life Balance Score          0
Training Date                    0
Training Program Name            0
Training Type                    0
Training Outcome                 0
Location                         0
Trainer                          0
Training Duration(Days)          0
Training Cost                    0
dtype: int64

In [402]:
df1.drop('ExitDate',axis =1,inplace = True) # droping the columns

In [403]:
df1.isna().sum()

Unnamed: 0                       0
FirstName                        0
LastName                         0
StartDate                        0
Title                            0
Supervisor                       0
ADEmail                          0
BusinessUnit                     0
EmployeeStatus                   0
EmployeeType                     0
PayZone                          0
EmployeeClassificationType       0
TerminationType                  0
TerminationDescription        1544
DepartmentType                   0
Division                         0
DOB                              0
State                            0
JobFunctionDescription           0
GenderCode                       0
LocationCode                     0
RaceDesc                         0
MaritalDesc                      0
Performance Score                0
Current Employee Rating          0
Employee ID                      0
Survey Date                      0
Engagement Score                 0
Satisfaction Score               0
Work-Life Balance Score          0
Training Date                    0
Training Program Name            0
Training Type                    0
Training Outcome                 0
Location                         0
Trainer                          0
Training Duration(Days)          0
Training Cost                    0
dtype: int64

In [404]:
df1['ExitDate'] = data_u['ExitDate']

In [405]:
df1.isna().sum()

Unnamed: 0                       0
FirstName                        0
LastName                         0
StartDate                        0
Title                            0
Supervisor                       0
ADEmail                          0
BusinessUnit                     0
EmployeeStatus                   0
EmployeeType                     0
PayZone                          0
EmployeeClassificationType       0
TerminationType                  0
TerminationDescription        1544
DepartmentType                   0
Division                         0
DOB                              0
State                            0
JobFunctionDescription           0
GenderCode                       0
LocationCode                     0
RaceDesc                         0
MaritalDesc                      0
Performance Score                0
Current Employee Rating          0
Employee ID                      0
Survey Date                      0
Engagement Score                 0
Satisfaction Score               0
Work-Life Balance Score          0
Training Date                    0
Training Program Name            0
Training Type                    0
Training Outcome                 0
Location                         0
Trainer                          0
Training Duration(Days)          0
Training Cost                    0
ExitDate                      1544
dtype: int64

In [406]:
df1.head(1)

,Unnamed: 0,FirstName,LastName,StartDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,EmployeeType,...,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Location,Trainer,Training Duration(Days),Training Cost,ExitDate
0,0,Uriah,Bridges,20-Sep-19,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,Contract,...,3,15-Jul-23,Leadership Development,Internal,Failed,South Marisa,Taylor Rodriguez,2,606.11,NaN

In [407]:
#drop all categorical value 
data_new = df1.select_dtypes(['Int64','Float64']) # slecet only the numeric value 
data_new

,Unnamed: 0,LocationCode,Current Employee Rating,Employee ID,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Duration(Days),Training Cost
0,0,34904,4,3427,1,2,3,2,606.11
1,1,6593,3,3428,2,1,5,4,673.02
2,2,2330,4,3429,1,2,1,2,413.28
3,3,58782,2,3430,5,5,4,3,663.78
4,4,33174,3,3431,2,5,3,5,399.03
...,...,...,...,...,...,...,...,...,...
3145,450,81607,3,3877,3,3,4,1,888.55
3146,2164,19215,4,2591,4,5,5,2,745.31
3147,2372,54859,2,2799,2,1,1,1,543.46
3148,2012,52238,5,2439,4,3,5,4,816.24
3149,270,51256,4,3697,3,4,1,2,982.33

In [408]:
# add columns in data set 
data_new ['new_score of satisfaction'] = data_new['Satisfaction Score']*0.1
data_new

,Unnamed: 0,LocationCode,Current Employee Rating,Employee ID,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Duration(Days),Training Cost,new_score of satisfaction
0,0,34904,4,3427,1,2,3,2,606.11,0.2
1,1,6593,3,3428,2,1,5,4,673.02,0.1
2,2,2330,4,3429,1,2,1,2,413.28,0.2
3,3,58782,2,3430,5,5,4,3,663.78,0.5
4,4,33174,3,3431,2,5,3,5,399.03,0.5
...,...,...,...,...,...,...,...,...,...,...
3145,450,81607,3,3877,3,3,4,1,888.55,0.3
3146,2164,19215,4,2591,4,5,5,2,745.31,0.5
3147,2372,54859,2,2799,2,1,1,1,543.46,0.1
3148,2012,52238,5,2439,4,3,5,4,816.24,0.3
3149,270,51256,4,3697,3,4,1,2,982.33,0.4

In [409]:
data_new ['new_score of work-life'] = data_new['Work-Life Balance Score']*0.1 #add new columns to the dataframe 
data_new

,Unnamed: 0,LocationCode,Current Employee Rating,Employee ID,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Duration(Days),Training Cost,new_score of satisfaction,new_score of work-life
0,0,34904,4,3427,1,2,3,2,606.11,0.2,0.3
1,1,6593,3,3428,2,1,5,4,673.02,0.1,0.5
2,2,2330,4,3429,1,2,1,2,413.28,0.2,0.1
3,3,58782,2,3430,5,5,4,3,663.78,0.5,0.4
4,4,33174,3,3431,2,5,3,5,399.03,0.5,0.3
...,...,...,...,...,...,...,...,...,...,...,...
3145,450,81607,3,3877,3,3,4,1,888.55,0.3,0.4
3146,2164,19215,4,2591,4,5,5,2,745.31,0.5,0.5
3147,2372,54859,2,2799,2,1,1,1,543.46,0.1,0.1
3148,2012,52238,5,2439,4,3,5,4,816.24,0.3,0.5
3149,270,51256,4,3697,3,4,1,2,982.33,0.4,0.1

In [410]:
data_new.drop(['new_score of satisfaction','new_score of work-life'],axis = 1, inplace = True ) # drop the columns form the dataset

In [411]:
data_new

,Unnamed: 0,LocationCode,Current Employee Rating,Employee ID,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Duration(Days),Training Cost
0,0,34904,4,3427,1,2,3,2,606.11
1,1,6593,3,3428,2,1,5,4,673.02
2,2,2330,4,3429,1,2,1,2,413.28
3,3,58782,2,3430,5,5,4,3,663.78
4,4,33174,3,3431,2,5,3,5,399.03
...,...,...,...,...,...,...,...,...,...
3145,450,81607,3,3877,3,3,4,1,888.55
3146,2164,19215,4,2591,4,5,5,2,745.31
3147,2372,54859,2,2799,2,1,1,1,543.46
3148,2012,52238,5,2439,4,3,5,4,816.24
3149,270,51256,4,3697,3,4,1,2,982.33

In [412]:
def ssclass(value):
    if value>=4:
        return 'very good satisfide'
    elif value>=3:
        return 'good satisfide'
    elif value>=2:
        return 'nice satisfide'
    else:
        return 'bad satisfide'
data_new['Satisfaction Score class'] = data_new['Satisfaction Score'].apply(ssclass)

In [413]:
df1.drop('Satisfaction Score class',axis = 1,inplace = True)

KeyError: "['Satisfaction Score class'] not found in axis"

In [ ]:
df1.head(2)

In [ ]:
data_new.head()

In [414]:
df1.isna().sum()

Unnamed: 0                       0
FirstName                        0
LastName                         0
StartDate                        0
Title                            0
Supervisor                       0
ADEmail                          0
BusinessUnit                     0
EmployeeStatus                   0
EmployeeType                     0
PayZone                          0
EmployeeClassificationType       0
TerminationType                  0
TerminationDescription        1544
DepartmentType                   0
Division                         0
DOB                              0
State                            0
JobFunctionDescription           0
GenderCode                       0
LocationCode                     0
RaceDesc                         0
MaritalDesc                      0
Performance Score                0
Current Employee Rating          0
Employee ID                      0
Survey Date                      0
Engagement Score                 0
Satisfaction Score               0
Work-Life Balance Score          0
Training Date                    0
Training Program Name            0
Training Type                    0
Training Outcome                 0
Location                         0
Trainer                          0
Training Duration(Days)          0
Training Cost                    0
ExitDate                      1544
dtype: int64

In [421]:
df1.shape

(3150, 39)

In [425]:
df1.dropna(subset=['TerminationDescription'],inplace = True) # drop all the missing value by using the dropna method

In [432]:
df2 = data_u.copy()

In [433]:
df2.isna().sum()

Unnamed: 0                       0
FirstName                        0
LastName                         0
StartDate                        0
ExitDate                      1544
Title                            0
Supervisor                       0
ADEmail                          0
BusinessUnit                     0
EmployeeStatus                   0
EmployeeType                     0
PayZone                          0
EmployeeClassificationType       0
TerminationType                  0
TerminationDescription        1544
DepartmentType                   0
Division                         0
DOB                              0
State                            0
JobFunctionDescription           0
GenderCode                       0
LocationCode                     0
RaceDesc                         0
MaritalDesc                      0
Performance Score                0
Current Employee Rating          0
Employee ID                      0
Survey Date                      0
Engagement Score                 0
Satisfaction Score               0
Work-Life Balance Score          0
Training Date                    0
Training Program Name            0
Training Type                    0
Training Outcome                 0
Location                         0
Trainer                          0
Training Duration(Days)          0
Training Cost                    0
dtype: int64

In [436]:
df2.dropna(subset = ['ExitDate'],inplace = True )

In [440]:
data_u.isna().sum()
df3 = data_u.copy()

In [441]:
df3.isna().sum()

Unnamed: 0                       0
FirstName                        0
LastName                         0
StartDate                        0
ExitDate                      1544
Title                            0
Supervisor                       0
ADEmail                          0
BusinessUnit                     0
EmployeeStatus                   0
EmployeeType                     0
PayZone                          0
EmployeeClassificationType       0
TerminationType                  0
TerminationDescription        1544
DepartmentType                   0
Division                         0
DOB                              0
State                            0
JobFunctionDescription           0
GenderCode                       0
LocationCode                     0
RaceDesc                         0
MaritalDesc                      0
Performance Score                0
Current Employee Rating          0
Employee ID                      0
Survey Date                      0
Engagement Score                 0
Satisfaction Score               0
Work-Life Balance Score          0
Training Date                    0
Training Program Name            0
Training Type                    0
Training Outcome                 0
Location                         0
Trainer                          0
Training Duration(Days)          0
Training Cost                    0
dtype: int64

In [462]:
#fill the null value 
#fill by mode,median,mean ect
#fill using method ffill for forward fill 
#fill using method bfill for backwars fill 
df3['ExitDate'] =df3['ExitDate'].bfill()#for backward fill

In [467]:
df3['TerminationDescription'] =df3['TerminationDescription'].ffill() # for forward fill

In [468]:
df3.isna().sum()

Unnamed: 0                    0
FirstName                     0
LastName                      0
StartDate                     0
ExitDate                      0
Title                         0
Supervisor                    0
ADEmail                       0
BusinessUnit                  0
EmployeeStatus                0
EmployeeType                  0
PayZone                       0
EmployeeClassificationType    0
TerminationType               0
TerminationDescription        6
DepartmentType                0
Division                      0
DOB                           0
State                         0
JobFunctionDescription        0
GenderCode                    0
LocationCode                  0
RaceDesc                      0
MaritalDesc                   0
Performance Score             0
Current Employee Rating       0
Employee ID                   0
Survey Date                   0
Engagement Score              0
Satisfaction Score            0
Work-Life Balance Score       0
Training Date                 0
Training Program Name         0
Training Type                 0
Training Outcome              0
Location                      0
Trainer                       0
Training Duration(Days)       0
Training Cost                 0
dtype: int64

In [472]:
mean = df3['Training Duration(Days)'].mean()

In [473]:
df3['Training Duration(Days)'].fillna(mean) # fill the misiing value by using the mean of its value

0       2
1       4
2       2
3       3
4       5
       ..
3145    1
3146    2
3147    1
3148    4
3149    2
Name: Training Duration(Days), Length: 3150, dtype: int64

In [474]:
df3.isna().sum()

Unnamed: 0                    0
FirstName                     0
LastName                      0
StartDate                     0
ExitDate                      0
Title                         0
Supervisor                    0
ADEmail                       0
BusinessUnit                  0
EmployeeStatus                0
EmployeeType                  0
PayZone                       0
EmployeeClassificationType    0
TerminationType               0
TerminationDescription        6
DepartmentType                0
Division                      0
DOB                           0
State                         0
JobFunctionDescription        0
GenderCode                    0
LocationCode                  0
RaceDesc                      0
MaritalDesc                   0
Performance Score             0
Current Employee Rating       0
Employee ID                   0
Survey Date                   0
Engagement Score              0
Satisfaction Score            0
Work-Life Balance Score       0
Training Date                 0
Training Program Name         0
Training Type                 0
Training Outcome              0
Location                      0
Trainer                       0
Training Duration(Days)       0
Training Cost                 0
dtype: int64

In [477]:
df3.dropna(subset= ['DOB','GenderCode'],inplace = True)

In [478]:
df3.isna().sum()

Unnamed: 0                    0
FirstName                     0
LastName                      0
StartDate                     0
ExitDate                      0
Title                         0
Supervisor                    0
ADEmail                       0
BusinessUnit                  0
EmployeeStatus                0
EmployeeType                  0
PayZone                       0
EmployeeClassificationType    0
TerminationType               0
TerminationDescription        6
DepartmentType                0
Division                      0
DOB                           0
State                         0
JobFunctionDescription        0
GenderCode                    0
LocationCode                  0
RaceDesc                      0
MaritalDesc                   0
Performance Score             0
Current Employee Rating       0
Employee ID                   0
Survey Date                   0
Engagement Score              0
Satisfaction Score            0
Work-Life Balance Score       0
Training Date                 0
Training Program Name         0
Training Type                 0
Training Outcome              0
Location                      0
Trainer                       0
Training Duration(Days)       0
Training Cost                 0
dtype: int64