In [49]:
# import laiberies
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [50]:
#load dataset 
data = pd.read_excel(r'/Users/sanjaymagar/Desktop/Code IT data analysis project /Ecommerce Sales Analysis.xlsx')

In [51]:
data.head(2)

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,2013,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2013-152156,2013,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [52]:
data_new = data[['Order Date','Sales','Profit']]
data_new

     Order Date     Sales    Profit
0    2013-11-09  261.9600   41.9136
1    2013-11-09  731.9400  219.5820
2    2013-06-13   14.6200    6.8714
3    2012-10-11  957.5775 -383.0310
4    2012-10-11   22.3680    2.5164
...         ...       ...       ...
9989 2011-01-22   25.2480    4.1028
9990 2014-02-27   91.9600   15.6332
9991 2014-02-27  258.5760   19.3932
9992 2014-02-27   29.6000   13.3200
9993 2014-05-05  243.1600   72.9480

[9994 rows x 3 columns]

In [53]:
data_new.isna().sum()

Order Date    0
Sales         0
Profit        0
dtype: int64

In [54]:
data_new.info()# datetime64[ns] order date must be in this

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order Date  9994 non-null   datetime64[ns]
 1   Sales       9994 non-null   float64
 2   Profit      9994 non-null   float64
dtypes: datetime64[ns](1), float64(2)
memory usage: 234.4 KB

In [55]:
df = data_new.copy()

In [56]:
#set the index
df.set_index('Order Date',inplace = True)

In [57]:
df.head(5)

               Sales    Profit
Order Date
2013-11-09  261.9600   41.9136
2013-11-09  731.9400  219.5820
2013-06-13   14.6200    6.8714
2012-10-11  957.5775 -383.0310
2012-10-11   22.3680    2.5164

# Resample Date

# Resample date in daily basis

In [58]:

daily_sales = df.resample('D').agg({'Sales':'sum'})
daily_sales

                Sales
Order Date
2011-01-04    16.4480
2011-01-05   288.0600
2011-01-06    19.5360
2011-01-07  4407.1000
2011-01-08    87.1580
...               ...
2014-12-27   814.5940
2014-12-28   177.6360
2014-12-29  1657.3508
2014-12-30  2915.5340
2014-12-31   713.7900

[1458 rows x 1 columns]

In [69]:
daily_profit = df.resample('D').agg({'Profit':'sum'}).reset_index()
daily_profit

     Order Date     Profit
0    2011-01-04     5.5512
1    2011-01-05   -65.9901
2    2011-01-06     4.8840
3    2011-01-07  1358.0524
4    2011-01-08   -71.9621
...         ...        ...
1453 2014-12-27    61.1202
1454 2014-12-28   -31.9742
1455 2014-12-29   253.1188
1456 2014-12-30   644.4338
1457 2014-12-31   101.5365

[1458 rows x 2 columns]

# Resample Date in monthly basis

In [60]:

#End of the month 
Mothly_end = df.resample('M').agg({'Profit':'sum','Sales':'sum'})
Mothly_end.head(5)

/var/folders/gk/8p2cy2r906j11_0stbnxqlb40000gn/T/ipykernel_8354/497956853.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  Mothly_end = df.resample('M').agg({'Profit':'sum','Sales':'sum'})

               Profit      Sales
Order Date
2011-01-31  2446.7711  13946.229
2011-02-28   865.7280   4810.558
2011-03-31   498.7299  55691.009
2011-04-30  3488.8352  28295.345
2011-05-31  2738.7096  23648.287

In [68]:
#start of the month 
Mothly_start = df.resample('MS').agg({'Profit':'sum','Sales':'sum'}).reset_index()
Mothly_start.head(5)

  Order Date     Profit      Sales
0 2011-01-01  2446.7711  13946.229
1 2011-02-01   865.7280   4810.558
2 2011-03-01   498.7299  55691.009
3 2011-04-01  3488.8352  28295.345
4 2011-05-01  2738.7096  23648.287

# Resample date in quartaly basis

In [70]:

#End of the quarter
q_end = df.resample('Q').agg({'Sales':['max','min']}).reset_index()
q_end.head(5)

/var/folders/gk/8p2cy2r906j11_0stbnxqlb40000gn/T/ipykernel_8354/2946510880.py:2: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  q_end = df.resample('Q').agg({'Sales':['max','min']}).reset_index()

  Order Date     Sales
                   max    min
0 2011-03-31  22638.48  0.852
1 2011-06-30   4164.05  1.365
2 2011-09-30   9449.95  0.876
3 2011-12-31   6999.96  0.898
4 2012-03-31   6354.95  1.112

In [63]:
#start of the quarter
q_start = df.resample('QS').agg({'Sales':['max','min'],'Profit':['mean','sum']})
q_start.head(5)

               Sales            Profit
                 max    min       mean         sum
Order Date
2011-01-01  22638.48  0.852  13.514996   3811.2290
2011-04-01   4164.05  1.365  28.581809  11204.0692
2011-07-01   9449.95  0.876  22.703407  12804.7218
2011-10-01   6999.96  0.898  28.773449  21723.9541
2012-01-01   6354.95  1.112  35.634391   9264.9416

#resample date on Yearly basis

In [64]:

#end of the year 
year_end = df.resample('Y').agg({'Sales':['max','min']})
year_end.head(5)

/var/folders/gk/8p2cy2r906j11_0stbnxqlb40000gn/T/ipykernel_8354/3482145491.py:2: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  year_end = df.resample('Y').agg({'Sales':['max','min']})

               Sales
                 max    min
Order Date
2011-12-31  22638.48  0.852
2012-12-31   6354.95  0.984
2013-12-31  17499.95  0.836
2014-12-31  13999.96  0.444

In [65]:
#start of the year 
year_start = df.resample('YS').agg({'Sales':['mean','sum'],'Profit':['max','min']})
year_start

                 Sales                  Profit
                  mean          sum        max        min
Order Date
2011-01-01  242.974159  484247.4981  4630.4755 -3701.8928
2012-01-01  223.849909  470532.5090  3177.4750 -2639.9912
2013-01-01  235.842570  608473.8300  8399.9760 -6599.9780
2014-01-01  221.134987  733947.0232  6719.9808 -3839.9904

In [66]:
year_start.reset_index(inplace = True) # reset index

In [67]:
year_start

  Order Date       Sales                  Profit
                    mean          sum        max        min
0 2011-01-01  242.974159  484247.4981  4630.4755 -3701.8928
1 2012-01-01  223.849909  470532.5090  3177.4750 -2639.9912
2 2013-01-01  235.842570  608473.8300  8399.9760 -6599.9780
3 2014-01-01  221.134987  733947.0232  6719.9808 -3839.9904

# resample weekly basis

In [73]:
weekly_basis = df.resample('W').agg({'Sales':'sum','Profit':'sum'})
weekly_basis

                 Sales     Profit
Order Date
2011-01-09   4818.3020  1230.5354
2011-01-16   3871.0190   722.9841
2011-01-23   3442.5400   301.0276
2011-01-30   1573.8680   180.5738
2011-02-06   1443.2080   311.2429
...                ...        ...
2014-12-07  27434.9380  1470.3319
2014-12-14  23308.4050   687.4551
2014-12-21  13010.6350  1607.4239
2014-12-28  21433.9480  3768.5680
2015-01-04   5286.6748   999.0891

[209 rows x 2 columns]

# monthly shifted

In [75]:
data_monthly = df.resample('M').agg({'Sales':'sum','Profit':'sum'})
data_monthly.head(5)

/var/folders/gk/8p2cy2r906j11_0stbnxqlb40000gn/T/ipykernel_8354/3468451935.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  data_monthly = df.resample('M').agg({'Sales':'sum','Profit':'sum'})

                Sales     Profit
Order Date
2011-01-31  13946.229  2446.7711
2011-02-28   4810.558   865.7280
2011-03-31  55691.009   498.7299
2011-04-30  28295.345  3488.8352
2011-05-31  23648.287  2738.7096

In [77]:
data_monthly['Sales_shifted'] = data_monthly['Sales'].shift(periods = 1,freq='M')

/var/folders/gk/8p2cy2r906j11_0stbnxqlb40000gn/T/ipykernel_8354/1083634835.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  data_monthly['Sales_shifted'] = data_monthly['Sales'].shift(periods = 1,freq='M')

In [78]:
data_monthly.head(5)

                Sales     Profit  Sales_shifted
Order Date
2011-01-31  13946.229  2446.7711            NaN
2011-02-28   4810.558   865.7280      13946.229
2011-03-31  55691.009   498.7299       4810.558
2011-04-30  28295.345  3488.8352      55691.009
2011-05-31  23648.287  2738.7096      28295.345

# Rolling Window

In [79]:
df

               Sales    Profit
Order Date
2013-11-09  261.9600   41.9136
2013-11-09  731.9400  219.5820
2013-06-13   14.6200    6.8714
2012-10-11  957.5775 -383.0310
2012-10-11   22.3680    2.5164
...              ...       ...
2011-01-22   25.2480    4.1028
2014-02-27   91.9600   15.6332
2014-02-27  258.5760   19.3932
2014-02-27   29.6000   13.3200
2014-05-05  243.1600   72.9480

[9994 rows x 2 columns]

In [80]:
#rolling mean
df['rolling_sales_mean'] = df['Sales'].rolling(window = 3).mean()
df

               Sales    Profit  rolling_sales_mean
Order Date
2013-11-09  261.9600   41.9136                 NaN
2013-11-09  731.9400  219.5820                 NaN
2013-06-13   14.6200    6.8714          336.173333
2012-10-11  957.5775 -383.0310          568.045833
2012-10-11   22.3680    2.5164          331.521833
...              ...       ...                 ...
2011-01-22   25.2480    4.1028          103.779333
2014-02-27   91.9600   15.6332          107.769333
2014-02-27  258.5760   19.3932          125.261333
2014-02-27   29.6000   13.3200          126.712000
2014-05-05  243.1600   72.9480          177.112000

[9994 rows x 3 columns]

In [82]:
#rolling sum
df['Rolling sum_profit']= df['Profit'].rolling(window=4).sum()
df

               Sales    Profit  rolling_sales_mean  Rolling sum_profit
Order Date
2013-11-09  261.9600   41.9136                 NaN                 NaN
2013-11-09  731.9400  219.5820                 NaN                 NaN
2013-06-13   14.6200    6.8714          336.173333                 NaN
2012-10-11  957.5775 -383.0310          568.045833           -114.6640
2012-10-11   22.3680    2.5164          331.521833           -154.0612
...              ...       ...                 ...                 ...
2011-01-22   25.2480    4.1028          103.779333            103.7670
2014-02-27   91.9600   15.6332          107.769333            104.1794
2014-02-27  258.5760   19.3932          125.261333             94.7762
2014-02-27   29.6000   13.3200          126.712000             52.4492
2014-05-05  243.1600   72.9480          177.112000            121.2944

[9994 rows x 4 columns]